name: Shaper
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Shaping the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070d10'
    - '#2e515d'
    - '#dddddd'
    - '#b1bdc2'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
